version: '3.8'

networks:
  metrics:
    name: opentelemetrydemo-network
    
services:
  prometheus:
    build: 
      context: ./scripts/prometheus
    ports:
      - 9090:9090
    networks:
      - metrics

  grafana:
    build: 
      context: ./scripts/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    networks:
      - metrics
  
  otel-collector:
    image: otel/opentelemetry-collector:0.89.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./scripts/otel-collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "8888:8888" 
      - "8889:8889" 
      - "13133:13133"
      - "4317:4317"
    networks:
      - metrics
      
  zipkin:
    image: openzipkin/zipkin:latest
    ports:
        - "9411:9411" 
    networks:
        - metrics